name: ECG-Bench CI/CD
run-name: ${{ github.actor }} is running tests 🚀
on: [push, pull_request]
jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-xdist
          
      - name: Install project in development mode
        run: |
          pip install -e .
          
      - name: List project structure
        run: |
          ls -la
          
      - name: Run core component tests
        run: |
          pytest -xvs tests/test_core_components.py
          
      - name: Run data loader tests
        run: |
          pytest -xvs tests/test_data_loaders.py
          
      - name: Run model tests
        run: |
          pytest -xvs tests/test_models.py
          
      - name: Run GPU compatibility tests (if available)
        run: |
          if [ $(python -c "import torch; print(torch.cuda.is_available())") == "True" ]; then
            pytest -xvs tests/test_gpu.py
          else
            echo "CUDA not available, skipping GPU tests"
          fi
          
      - name: Run transformers tests (if available)
        run: |
          if [ -d "transformers" ]; then
            pytest -xvs tests/test_transformers.py
          else
            echo "Transformers directory not found, skipping transformers tests"
          fi
